### ISSUE TITLE
Would you consider adding 2D navigation?

### ISSUE THREAD

**Issue by classicrob** [crazko/krystal#1]
Hi! Love this, thank you for doing this. Would you consider doing 2d navigation? Imagine if every time you clicked on a page link, it was added vertically into the slot to the right, instead of straight up replacing everything that was already to the right. https://www.freecodecamp.org/news/lossless-web-navigation-spatial-model-37f83438201d/ 
![Roam layout rework 2](https://user-images.githubusercontent.com/46608303/81975845-de20e000-95e4-11ea-9bcf-fb27f9ea6e16.png) 

![Roam layout rework](https://user-images.githubusercontent.com/46608303/81975838-dbbe8600-95e4-11ea-9fcd-51a98bb6d26a.png)

**Comment by classicrob** [comment]
2D navigation- Horizontal to follow a train of thought, vertical to open up new trains of thought from the same previous starting point. Current way of preserving previous trains of thought is to open an entirely new tab.

**Comment by crazko** [comment]
Hi, thanks for feedback! I haven't implemented (yet) the replacing functionality as Andy's notes has. Instead, new tiddlers are always open to the right side of the parent tiddler, or you are scrolled to the position of that tiddler, if it is already open. Which is basically the same behavior TiddlyWiki has, but horizntal.

2D navigation you'are mentioning would be difficult to implement, I'm afraid. It would need to function with multiple story rivers and keep horizontal scrolling in sync. Currently, I'm not convinced by this idea.

**Comment by crazko** [comment]
I do not consider to implement such behavior, so I'm closing this for now.
