### ISSUE TITLE
Ideas for Andy's hover effect?

### ISSUE THREAD

**Issue by garrettvercoe** [crazko/krystal#10]
Hey, 

Awesome theme! Have you thought about an easy way to integrate the preview feature from Andy's version? You can see a similar implementation on [Anne-Laure's site](https://www.mentalnodes.com/). If you don't currently have the bandwidth, I'd be open to taking a stab at it.

**Comment by crazko** [comment]
Hi, thanks! Actually, there is a discussion about the popups here https://github.com/crazko/krystal/issues/4.

From my point of view, it would be great if the plugins that already provide this functionality changed their implementation about popups positioning (as their implementation is not that flexible) to be compatible also with this plugin. I think it's better then implement it as a part of this plugin.

So far, I know about two such plugins ([Refnotes](https://kookma.github.io/Refnotes/), [Preview](https://github.com/tobibeer/tw5-preview)). This js library is capable of such functionality [Tippy.js](https://atomiks.github.io/tippyjs/).

Would be great if you could look into that!

**Comment by crazko** [comment]
Closing in favor of #4. Please, keep further discussion there.
