### ISSUE TITLE
An option to compare tiddlers by introducing something similar to Two story view or Muuritouch 

### ISSUE THREAD

**Issue by arunnbabu81** [crazko/krystal#12]
My current TW is made based on Krystal. I love your concept. Full width view has made it even better. 

Only thing I find lacking is its difficult to compare two related Tiddlers side by side. This may be done by introducing something similar to two story view or Muuritouch. A button can be added in the top menu to switch between the horizontal story river and two-story view or  something like Muuritouch view. Or else an additional button can be provided in the view toolbar of the tiddlers for shifting their position. 

I don't have much technical knowledge in this matter. These are just a few suggestion. Don't know whether its implementable or not.

**Comment by crazko** [comment]
Hi, could you please provide some example? I didn't find how Muuritouch looks like.

**Comment by arunnbabu81** [comment]
http://muritest-reloaded.tiddlyspot.com. I was mentioning about arranging tiddlers like tiles as in Muuritouch (by pressing some buttons provided in the top bar)

**Comment by crazko** [comment]
Thanks for the example. I'm afraid I do not see the added value in implementing such feature as all tiddlers are located side-by-side in Krystal already.

When two tiddlers are related, I assume they are interconnected, so it is just a matter of one click on the link to open second tiddler to the side. Or am I missing something?

Krystal is a re-implementation of [Andy Matuschak's note system](https://notes.andymatuschak.org), where I\m satisfied with its simplicity.

**Comment by arunnbabu81** [comment]
I will report back if I find any difficulty in using it in the current form.

**Comment by crazko** [comment]
Thank you. I'll close this for now. We can re-open in the future if needed.
