### ISSUE TITLE
Stacking of tiddlers on the left side doesn't reveal tiddlers title unlike one the right side [Safari browser]

### ISSUE THREAD

**Issue by arunnbabu81** [crazko/krystal#13]
When multiple tiddlers are opened, stacking of tiddlers on the left side doesn't reveal the tiddlers title unlike on the right side.
I am attaching some images for reference.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/67494083/91858780-49bbb580-ec87-11ea-97ff-d29176317c12.png">
In the first image, the first two tiddlers on the left side are in focus while the unfocussed tiddlers one the left side are stacked together with their titles revealed.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/67494083/91859016-930c0500-ec87-11ea-9e98-aafde9d2e3ec.png">
In the second image, the last two tiddlers on the left side are in focus, while the unfocussed tiddlers on the left side are neither shown as in stack nor their title are revealed.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/67494083/91859603-4674f980-ec88-11ea-893f-91382c20d0c8.png">

This third image is showing that one tiddler stacked on the right is not showing its title (third one from the right) because I had scrolled to the bottom of that tiddler before moving to another tiddler.

Can this be corrected?

**Comment by crazko** [comment]
Thanks for the report. Could you please help me with the reproduction of this issue? The tiddler title should be present even when you scroll down, but it may be missing in following cases:

- tiddler is in edit mode
- you scroll horizontally to quickly so the animation "does not have a time to react"

Could those be causing the issue you have? Or can you describe some steps to reproduce?

**Comment by arunnbabu81** [comment]
1. I just opened 5 to 6 tiddlers at the same time 
2. Scrolled vertically to the bottom of the tiddler with contents extending more than the vertical length of the screen(not in edit mode).
3. Scroll horizontally.
4. Now the title of the tiddler mentioned inn step 2 is either cut off or not displayed (depending on the vertical length of contents in that tiddler)

**Comment by arunnbabu81** [comment]
"When multiple tiddlers are opened, stacking of tiddlers on the left side doesn't reveal the tiddlers title unlike on the right side"
I am seeing this only when I open TW in safari .......its working nicely in tiddlydesktop, chrome/edge browsers and even in tiddloid android app and I love the way Krystal behaves in android tablet. Its very user friendly. 

Few points which I noted which can even improve Krystal are:
1. Providing a keyboard shortcut for going into and coming out of the maximised state of a tiddler
2. Suppose a tiiddler is open in its maximised state and i clicked on a link within that tiddler, the linked tiddler won't be seen unless i come out of the maximised state. Can there a option to open those linked tiddlers without coming out of the maximised state - either by opening them in a pop up or as a spilt window. By split window I mean that the already opened tiddler which was in the maximised state should move to the left half of the screen and the linked tiddler which I clicked should open in the right half of the screen if I click on the link using 'shift+click'. If I open anymore linked tiddlers, they should replace the tiddler occupying the right of the screen.

**Comment by crazko** [comment]
> 1. Providing a keyboard shortcut for going into and coming out of the maximised state of a tiddler

That's a good idea.

> 2. Suppose a tiiddler is open in its maximised state and i clicked on a link within that tiddler, the linked tiddler won't be seen unless i come out of the maximised state. Can there a option to open those linked tiddlers without coming out of the maximised state - either by opening them in a pop up or as a spilt window. By split window I mean that the already opened tiddler which was in the maximised state should move to the left half of the screen and the linked tiddler which I clicked should open in the right half of the screen if I click on the link using 'shift+click'. If I open anymore linked tiddlers, they should replace the tiddler occupying the right of the screen.

I'm afraid by implementing this it'll start to be a bit over-complicated. If anything, by clicking on the link in the maximised state it returns back to the default state is something I can imagine.

**Comment by arunnbabu81** [comment]
Keyboard shortcut for going into and coming out of the maximised state of a tiddler will be very handy. 

"Clicking on the link in a tiddler in the maximised state returns back to the default state" - Providing this option also will definitely enhance the workflow.

I also I want a keyboard shortcut to not close tiddlers to the right. Currently if we open multiple tiddler from recents or if we open multiple links from a single tiddler, the second opened tiddler will replace the first opened tiddler and so on. But if you can configure it like this it will be better - just 'clicking' on the links will behave normally, but if we 'shift-click' on the link, the tiddlers to the right should not close. I know that there is an option to configure it in the settings. But it affects the workflow if we have to go to settings every time to change it.

Only problem now remaining will be when 4 or more tiddlers are open simultaneously, it will be difficult to see and compare two non-adjacent tiddlers. For example, if I want to see 2nd and 5th tiddler simultaneously, its not possible in the current set up. But this is not a big problem. I have encountered such situation once in a while only. Can you think of any workaround for this? 

Also, do you find dropdown option for the contents in the the topbar useful? I have found such a setup in mentat story river (https://thesherwood.github.io/Mentat/) and at http://tongerner.tiddlyspot.com. 

I am very happy using Krystal and I have built my personal tiddlywiki based on Krystal. 
The plug ins which I use most commonly are flibbles/relink, snowgoon88/edit-comptext, linonetwo/copy-on-select, souk21/command palette, sq/editor-autolist. I also found these plug ins very useful - wikilabs/multicol-dropdown and edit-tabs, kookma/utility, tobibeer/preview, danielo515/ContextPlugin, TWaddle /richlinks, jd/fullscreen-editor, kebi/tiddlyresearch-references and twitter plug in.

**Comment by crazko** [comment]
Let's discuss all the other things in a separate issues.

**Comment by crazko** [comment]
If someone is able to investigate this issue (stacking in the left side) in Safari browser, let me know.

**Comment by ericworks** [comment]
This issue can be reproduced on Firefox 84. I did not test it with Safari, but I believe the behaviour on Firefox is similar with Safari --- The stacked tiddlers' title are not shown (blank). 

I investigate the class name and find out that the class name ` krystal-tiddler__frame--overlay` and `krystal-tiddler__frame--hide` are not added to the stacked tiddlers' title DIV. This may imply that the condition check for stacking tiddlers is not met due to some reasons.

I debug the code in `plugin.js`, and notice the `tiddlerPadding` has different value on Chromium and Firefox --- correct value on Chromium and `0` on Firefox. With further investigation on the `window.getComputedStyle(tiddlers[0])` function, I finally figure out that this is the issue root. Below are the returned values on Chromium:

```Json
...,
padding: "31px"
paddingBlock: "31px"
paddingBlockEnd: "31px"
paddingBlockStart: "31px"
paddingBottom: "31px"
paddingInline: "31px"
paddingInlineEnd: "31px"
paddingInlineStart: "31px"
paddingLeft: "31px"
paddingRight: "31px"
paddingTop: "31px"
...
```

And below are the returned values on Firefox:

```Json
...,
padding: ""
"padding-block": ""
"padding-block-end": "31px"
"padding-block-start": "31px"
"padding-bottom": "31px"
"padding-inline": ""
"padding-inline-end": "31px"
"padding-inline-start": "31px"
"padding-left": "31px"
"padding-right": "31px"
"padding-top": "31px"
paddingBlock: ""
paddingBlockEnd: "31px"
paddingBlockStart: "31px"
paddingBottom: "31px"
paddingInline: ""
paddingInlineEnd: "31px"
paddingInlineStart: "31px"
paddingLeft: "31px"
paddingRight: "31px"
paddingTop: "31px"
...
```

There is a similar issue [here](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/591), stating that the padding property only works for Chromium based browser. The problem seems that Firefox treat `height`, `width`, `padding` [differently](https://developer.mozilla.org/en-US/docs/Web/CSS/used_value#difference_from_computed_value). 

I attempt to modify the code in `plugin.js` and change it into `window.getComputedStyle(tiddlers[0]).paddingRight.slice(0, -2)` in order to verify the assumption. It turns out that after changing the paddingRight, the stacking title shows as expected on Firefox (Chromium too).

This is quite an ad-hoc solution (I guess). Not sure if any better solution to get the padding values from the plugin settings directly.

**Comment by crazko** [comment]
> This is quite an ad-hoc solution (I guess). Not sure if any better solution to get the padding values from the plugin settings directly.

It'd be possible to get it from the settings, you are right. Another way would be to get custom CSS property directly (I just learned it's also possible):

```js
window.getComputedStyle(tiddlers[0]).getPropertyValue('--tiddler-padding')
```

Your solution works, so let's stick with that :) thanks
