### ISSUE TITLE
Need a better referencing or linking than default 

### ISSUE THREAD

**Issue by arunnbabu81** [crazko/krystal#14]
There is a need for a better referencing or linking than the default linking in Krystal.
I will give some examples using 4 different linking plug ins for the same tiddlers

1. Using default linking in Krystal.
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/67494083/91861171-25150d00-ec8a-11ea-8665-d2661896bbf7.png">
Here only the direct backlinks are shown without highlighting of the linked words and without ability to collapse the references.

2. Using stroll or tiddlyblink (found in Goodies for Stroll - https://giffmex.org/stroll/goodies.html)
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/67494083/91861432-6ad1d580-ec8a-11ea-90dd-737b21700188.png">
Here also only the direct backlinks are shown, but there is highlighting of the linked words and ability to collapse the reference.

3. Using TWCrosslinks (found in Drift - https://akhater.github.io/drift/)
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/67494083/91862507-ad47e200-ec8b-11ea-8800-b392fe4ed772.png">

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/67494083/91861627-ad93ad80-ec8a-11ea-9fa1-5b57040da378.png">

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/67494083/91864201-91454000-ec8d-11ea-84d8-448cdbf94a25.png">

Here there is backlinks, free links, tags and keywords with pop up showing highlighting of linked words and ability to collapse the reference. But there pop up could be implemented better I guess.

4. Seen in early version of tiddlyresearch (https://kebifurai.github.io/TiddlyResearch/)
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/67494083/91862164-3ca0c580-ec8b-11ea-8a86-63dd904a3b86.png">

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/67494083/91862868-1a5b7780-ec8c-11ea-94a6-07cb74967222.png">

Here they provide 4 types of references - tags, direct backlink, mention in the title of a note, mention in the body text of a node and each of them are colour coded. Then there is pop up mechanism using tobibeer preview on hovering over the links. 

I was just sharing my thoughts. I prefer something which is a mix of TWCrosslinks or tiddlyresearch. But tobibeer preview plug in is not compatible with Krystal if we open more than two tidldlers. Hope you can make a better referencing in Krystal.

**Comment by crazko** [comment]
Thank you for your thoughts. Just for a reference, here's what I said about this pluginin #12:

> Krystal is a re-implementation of [Andy Matuschak's note system](https://notes.andymatuschak.org), where I\m satisfied with its simplicity.

But I think that some settings for References might be valuable, so I'll think about it. But please, bear in mind it is not a priority for me in this project.

As for popup/preview, follow the discussion in #4 - tl;dr: I do not want to implement it directly into Krystal, better would be some general plugin providing only such functionality, but without issues :)

**Comment by arunnbabu81** [comment]
Any improvement is appreciated. Thanks for the comments.
