### ISSUE TITLE
Manually reorder tiddlers in river

### ISSUE THREAD

**Issue by keelancook** [crazko/krystal#15]
Still loving the theme, by the way. The thought crossed my mind today, though, to raise an issue for a potential enhancement. It's not a major thing, but I thought I'd share and see if it was something you also thought beneficial.

I think it would make my use cases better if I could manually reorder the tiddlers in my river.

Currently, I use Krystal set to not close tiddlers to the right. I often want several related tiddlers open that contain notes and fragments while I'm writing in another tiddler. The ability to move them around in order would be a great benefit so I could compare two specific ones side by side without having to close several and reopen them in a different order.

Optionally, I could switch the setting to close tiddlers to the right if there was an option to override this behavior with a keyboard shortcut (like shift+click). In other words, the default action would be to close tiddlers to the right when clicking a link in a tiddler, but if I had a list of tiddlers and wanted them all open, I could shift+click on each entry in the list and they would all open in the order I clicked. 

Let me know if that needs further clarification. I don't know if you would see that as an improvement in behavior, or if it's even possible to implement. But, it crossed my mind today, and I wanted to share.

Thanks again for your work on this!

**Comment by keelancook** [comment]
Just found out this is actually already possible with a behavior baked into TiddlyWiki. Apparently, you can reorder the tiddlers in the river by going to the open tab in the sidebar and dragging and dropping to order them there. That moves them around in the river. I had no idea.

Also, it works great with Krystal already. No need to adjust anything!

**Comment by crazko** [comment]
I've just recently found that as well! Glad it's enough, because such drag n' drop feature would be problematic, I think.

But, I like the idea to skip closing tiddlers when clicking link together with some pressed key. So I will keep this open.

Thanks for suggestions ;)

**Comment by keelancook** [comment]
Sure thing. I'm rooting for your work!

**Comment by crazko** [comment]
Here is an another way to reorder open tiddlers - dropdown in the header - you can find setup instructions in https://github.com/crazko/krystal/issues/21#issuecomment-754664144.

![image](https://user-images.githubusercontent.com/1255989/103813561-94e43b80-5060-11eb-877a-3b9ea3a64edc.png)

**Comment by crazko** [comment]
Closing this as original question should be answered :)

Discussion about shortcuts will be held in #21
