### ISSUE TITLE
When clicking a link inside the Import tiddler all the other tiddlers close

### ISSUE THREAD

**Issue by kebifurai** [crazko/krystal#16]
This happened to me when I tried to import an image

**Comment by crazko** [comment]
Sounds like backed-in feature of Krystal - by default, clicking on the link closes all tiddlers to the right. You can [disable it in the settings](https://crazko.github.io/krystal/#%24%3A%2FControlPanel:%24%3A%2FControlPanel%20Krystal%20%24%3A%2Fplugins%2Frmnvsl%2Fkrystal%2Fsettings).
