### ISSUE TITLE
Feature: add arrow key navigation

### ISSUE THREAD

**Issue by kebifurai** [crazko/krystal#17]
I really like the horizontal view but one of its downsides is that it heavily relies on the bottom scroll bar.
When having more than 3 documents opened it would be great if you could navigate using the left/right arrow keys, something like this https://github.com/MaxGyver83/tw5-keyboard-navigation

Let me know what you think!

**Comment by crazko** [comment]
That's a nice plugin! Have you already tried it with Krystal? But maybe it's tied to top-to-bottom view...

Sidenote: besides scrollbar you can use touchbar, if possible, then the navigation is pretty smooth :)

**Comment by kebifurai** [comment]
The keyboard navigation plugin works but doesn't update the Krystal animations, causing the side tiddlers to be hidden under the tiddler next to them.

The touchbar also works great but you still need to move your hand from the keyboard to the mouse.

**Comment by arunnbabu81** [comment]
https://github.com/Jermolene/TiddlyWiki5/issues/4782#issuecomment-667108188

You can try this method by BTC. I extracted the tiddlers for keyboard navigation from this file and is using it in my TW file which is based on Krystal. It works well for me

**Comment by crazko** [comment]
@kebifurai - have you been able to try mentioned solution?

**Comment by kebifurai** [comment]
@crazko Yes, thank you. The solution posted by @arunnbabu81 is 100% compatible with krystal.

**Comment by crazko** [comment]
I tried it myself, this is great! I played a bit with active tiddler styling, as border causes small content shift:

![image](https://user-images.githubusercontent.com/1255989/96774382-33f48200-13e6-11eb-9699-f4f677d9cd1d.png)

Use it, if you like:

```
tags: $:/tags/Stylesheet
title: $:/_Styles
type: application/x-tiddler

\define style-focused-tiddler()
[data-tiddler-title="$(cssEscapedTitle)$"].tc-tiddler-frame::before {
display: block;
content: "";
height: 2px;
width: 100%;
position: absolute;
background: <<color primary>>;
top: 0;
left: 0;
}
\end

<$set name="cssEscapedTitle" value={{{ [{$:/HistoryList!!current-tiddler}escapecss[]] }}}>
<<style-focused-tiddler>>
</$set>
```
