### ISSUE TITLE
I really love this theme!

### ISSUE THREAD

**Issue by tomcritchlow** [crazko/krystal#2]
It's the first Tiddly theme that actually looks functional and pleasing to the eye. I added the theme to my node install and it all just works:

https://glitch.com/~helpful-foil-exhaust

Would love to help out / learn more or just generally cheer you on as you build this out. I don't know much about Tiddly but excited to learn and experiment with it.

**Comment by crazko** [comment]
Hi, thanks for the kind words! I'm happy it's working for you. If you find any bugs, you can let me know here, or try to fix them :)

It's possible to clone the repository and `npm install`. All plugin files are located in `./plugins/rmnvsl/krystal` directory. With `npm start` you start TW locally. You are free to experiment.

By the way, I came across you blog while doing research on evergreen notes. Like your theme and articles. Looking forward to read your Strategy book!

**Comment by tomcritchlow** [comment]
Thanks - this is great.

My glitch install above is dragging your theme into tiddlyblink but it seems to lose the typeahead feature when linking to pages. Possible to add that back?

I'm trying to get my head around TW development but still a complete n00b

**Comment by crazko** [comment]
TiddlyBlink is a different plugin, isn't it? What do you mean by "typeahead"?

**Comment by tomcritchlow** [comment]
Yes it is - wasn't sure if some features / plugins would be carried over when I installed this theme? As mentioned - TW noob over here...

The typeahead feature is an auto-complete on adding links. Looks like this:

![image](https://user-images.githubusercontent.com/474894/82221980-ae2c5200-98ee-11ea-9108-4cf5e8d24788.png)

**Comment by crazko** [comment]
This plugin doesn't contain any direct dependencies. You have to install
them directly. I recommend
https://crazko.github.io/krystal/#Recommended%20plugins , there's also one
with the feature you're looking for.

**Comment by tomcritchlow** [comment]
Oh this is great - works perfectly. Also I see you added some mobile styling! Love it.

**Comment by crazko** [comment]
Yes, and also an option that close already open tiddlers (like in [Andy Matuschak's system](https://notes.andymatuschak.org/)). Enjoy :)

**Comment by tomcritchlow** [comment]
Would you be ok if I blogged about this?

**Comment by crazko** [comment]
I'd be really happy!

**Comment by tomcritchlow** [comment]
Here we go!

https://tomcritchlow.com/2020/05/19/tiddlyblink-krystal/

Thanks!

**Comment by crazko** [comment]
That's great, thanks :)

**Comment by fkohrt** [comment]
Hi @crazko, looks great indeed! Reminds me of Ward Cunningham's [smallest federated wiki](https://github.com/fedwiki/wiki) ([example](http://fed.wiki.org/)) :)

**Comment by crazko** [comment]
Thank you @fkohrt! Indeed, the concept looks very similar. Maybe Andy, for his [own system](https://notes.andymatuschak.org/), took inspiration from this wiki you mentioned :)

**Comment by avks** [comment]
I was looking for a plugin that gives me _only_ bi-directional linking. Tried tiddlyblink but it is too opinionated and bloated, imho. @crazko, yours is more use-friendly and less bloated. Thanks a bunch for this gift to the community. ✌🏻

**Comment by crazko** [comment]
Thank you very much for your feedback! I'm happy you find it useful.
Though, I need to give credit to tiddlyblink - I've learned a lot from its
own implementation.
If you have any ideas for improvements or find a bug, please, let me know.

**Comment by crazko** [comment]
Closing to tidy up issues, thanks all for your positive feedback.
