### ISSUE TITLE
Error while using with markdown plugin

### ISSUE THREAD

**Issue by dummifiedme** [crazko/krystal#20]
I have been using this plugin for markdown, but krystal isn't going along with it.
https://github.com/anstosa/tw5-markdown
Can you please look into it?

**Comment by crazko** [comment]
Can you please elaborate what's not working or provide some example?

**Comment by dummifiedme** [comment]
This.
![image](https://user-images.githubusercontent.com/68785729/99854394-c08f8d00-2baa-11eb-8976-a0310d806eef.png)

**Comment by dummifiedme** [comment]
@crazko is there anything that can be done?
I would really like to use Krystal, but my notes are predominantly in markdown.

**Comment by crazko** [comment]
I'll try to look into it in the upcoming days.

**Comment by crazko** [comment]
I've just tried clean Krystal, added tw5-markdown and opened it with a tiddler containing markdown syntax without any issue.

You sure the problem isn't elsewhere?

**Comment by crazko** [comment]
I've also tried it on Node.js setup (as I can see from your image, that you have also tried it like that).

**Comment by dummifiedme** [comment]
I will try again. But since it was not working and throwing error, I began
adding and removing plug-ins I had in my info file. And it didn't work
explicitly with markdown Plugin. For rest of the plug-ins, it worked fine.
There weren't many plug-ins anyway, just 2 basic from the official
plug-ins, relink, and markdown.


And yes, I was using node version.

I will soon update you.

I am having another problem though, I was hosting the wiki on github pages,
and the Krystal theme is not at all visible on the address. Files and
tiddlers are all updated after each push, but Krystal fails to appear
there. I don't know where the problem there.

**Comment by crazko** [comment]
> I will soon update you.

I will reopen the issue, when you provide more feedback, as there is nothing more I can do now.

> I am having another problem though, I was hosting the wiki on github pages,
> and the Krystal theme is not at all visible on the address. Files and
> tiddlers are all updated after each push, but Krystal fails to appear
> there. I don't know where the problem there.

Please, open a new issue with more detailed info about this problem. Link to the repository would be really helpful. You can also check how this repository is set up - it uses [github actions to publish to github pages](https://github.com/crazko/krystal/blob/master/.github/workflows/build.yml).
