### ISSUE TITLE
Search results don't display when running under TW Release 5.1.23

### ISSUE THREAD

**Issue by nynj** [crazko/krystal#22]
<img width="271" alt="krystalSearchErrror" src="https://user-images.githubusercontent.com/899762/103450381-90480d80-4c83-11eb-83ab-ee2621ccb3f8.png">

Note there are 10 matches found, but none shown in the results list.  Disabling Krystal returns search results to expected.  Image via TiddlyDesktop.

**Comment by crazko** [comment]
Hi, thanks for a report. I confirm that this happens on a new version of TW `5.1.23`, but not on the previous one. Need to investigate why this is the case.

**Comment by crazko** [comment]
Please, update Krystal to version `0.3.2`

**Comment by nynj** [comment]
Validated
