### ISSUE TITLE
Separate backlinks from storyview 

### ISSUE THREAD

**Issue by ejemba** [crazko/krystal#27]
Hello thank you for your awesome work !

In term of layout this is my best experience so far in TW world !

This is why I ask if it could be possible to separate both features (making 2 plugins)
* Horizontal Layout
* Backlinks 

From my point of view I do not need back links.

Thank you

**Comment by crazko** [comment]
Hi Epo, I'm glad you like it.

I'm going to implement more options for backlinks, also with a possibility to turn them off. Until then, you can easily hide them by:

1. search for tiddler `$:/plugins/rmnvsl/krystal/references`
1. edit it and remove tag `$:/tags/ViewTemplate`
1. save

**Comment by ejemba** [comment]
@crazko Thank You ! 
Your fix helps me to remove the backlinks

**Comment by crazko** [comment]
Great to hear that!
