### ISSUE TITLE
Help needed to hide the header of Krystal in mobile only

### ISSUE THREAD

**Issue by arunnbabu81** [crazko/krystal#28]
I am using a [hack](https://groups.google.com/g/tiddlywiki/c/8VH0bpdJ2ig/m/_WA2atojCAAJ) given by Nicolas Petton in TW google group to enable his [NoteBook theme](https://nicolas.petton.fr/tw/notebook.html) only in mobile (not in desktops). But the header of Krystal is persisting and partly hiding the sidebar when I open the sidebar in mobile (with notebook theme active). Is there any way to hide the header only  in mobiles ? I am attaching a demo wiki with relevant tiddlers set as default home page tiddlers.

[Demo.html.zip](https://github.com/crazko/krystal/files/6245056/Demo.html.zip)

**Comment by crazko** [comment]
Hi, although I cannot reproduce the problem you described you can hide header for small screens with this change:

![image](https://user-images.githubusercontent.com/1255989/113518857-26dce100-9589-11eb-8589-bb75df915a75.png)

**Comment by arunnbabu81** [comment]
Thank you
