### ISSUE TITLE
Make it possible to disable backlinks feature

### ISSUE THREAD

**Issue by k0ral** [crazko/krystal#29]
Would it be possible to add a tickbox in plugin' settings to disable backlinks display (`$:/plugins/rmnvsl/krystal/references`) ?
This can conflict with other plugins that also offer this feature, and is quite independent from the other features of this plugin.

**Comment by crazko** [comment]
I've added such option to settings, please update to version `0.4.0`.

Can you please name some other plugins with backlinks functionality?

**Comment by k0ral** [comment]
Thanks for the quick reaction.
[Stroll](https://giffmex.org/stroll/stroll.html) also provides backlinks functionality.

**Comment by TeddyDD** [comment]
[TWCrossLinks](https://akhater.github.io/drift/#%24%3A%2Fak%2Fplugins%2FTWCrossLinks)

**Comment by arunnbabu81** [comment]
I have mentioned about three plug ins in this comment from an [similar issue](https://github.com/crazko/krystal/issues/14#issue-690192222). 

1. Stroll - https://giffmex.org/stroll/stroll.html#Linking%20in%20Stroll%2C%20part%202
2. Drift - https://akhater.github.io/drift/#%24%3A%2Fak%2Fplugins%2FTWCrossLinks
3. Tiddlyresearch - https://kebifurai.github.io/TiddlyResearch/#%24%3A%2Fplugins%2Fkebi%2Ftiddlyresearch-references or https://kebifurai.github.io/TiddlyResearch/#Backlinking%20and%20references

 There are two similar plug ins:
1. TOC generic - https://hchaase.github.io/HC-Plugins/#TOC-Generic%20Introduction - the one which I use currently
2. Roam like instance rr-tw5 - https://rr-tw5.github.io/#Linked%20References%20and%20Unlinked%20References

Hope this helps.
