### ISSUE TITLE
Screen doesn't move further to the right when new pages are opened.

### ISSUE THREAD

**Issue by jakob1111** [crazko/krystal#3]
As soon as more tiddlers are opened than fit onto the screen, the view remains focussed on the current tiddler instead of moving further to the right. In other words, the newly opened tiddlers are not visible unless one scrolls manually further to the right.

For example, at https://notes.andymatuschak.org/ the view moves automatically further to the right which I think would make a lot of sense.

PS: I really love your implementation so far!

PPS: I just discovered that the newly opened page is scrolled into view if the link is clicked a second time. Clicking it once opens the page. Clicking it a second time scrolls it into view. I'm not sure if this is intentional

**Comment by crazko** [comment]
Hi, thanks for your feedback! This behavior is not intentional, I just haven't figured it out so far. The main reason for that is the smooth animation, when new tiddler comes into the scene.

I will work on it, as it's something I really want to be solved :)

**Comment by crazko** [comment]
In the meantime, you can try to set **Animation duration** in Control Panel > Info > Basics or in `$:/config/AnimationDuration` to "0". Not the best experience, but it's somehow working.
