### ISSUE TITLE
[IDEA] Use fixed with for Searchbox 

### ISSUE THREAD

**Issue by kookma** [crazko/krystal#30]
The search box at top right move left when user starts entering keywords and TW found some tiddlers on deleting the inputs the searchbox get smaller again! This expanding/contracting is annoying see below gif.

![img_87_%pn](https://user-images.githubusercontent.com/830394/115652185-fb584580-a341-11eb-9d80-22aa12336cd1.gif)

**Suggestion**
Use fixed width search box and dropdown or relocate the searchbox as Notebook from Nicolas Petton 
https://nicolas.petton.fr/tw/notebook.html

**Comment by crazko** [comment]
Hi Mohammad, thanks for your ideas - all of them are straight to the point. I will get back to them in the upcoming days.
