### ISSUE TITLE
[IDEA] Header items bad tiddler names

### ISSUE THREAD

**Issue by kookma** [crazko/krystal#31]
Some shortcuts are  put on the header to replicate Tiddlywiki Sidebar items like

- $:/core/ui/SideBar/Open
- $:/core/ui/SideBar/Recent
-  etc.

When user click on them and open one of them he/she sees something like below

![img_88_chrome](https://user-images.githubusercontent.com/830394/115652559-bbde2900-a342-11eb-983b-2eec06f2d329.png)

Look at the ugly tiddler title. In original design of Tiddlywiki, these titles are replaced by captions when they are open at the sidebar

**Workaround**
* Use other tiddlers for header item for example `Open` instead of  `$:/core/ui/SideBar/Open` as below
* * create a new tiddler
* * name: `Open`
* * tag: `$:/tags/SideBar`
* * text:` {{$:/core/ui/SideBar/Open}}`

**Solution**
The sidebar items need to be treated in a better way. In other words Sidebar items should not be opened like an ordinary tiddler in the story river

- One solution can be what https://nicolas.petton.fr/tw/notebook.html uses.
- Other solution can be to open a tiddler contains horizontal tabs each replicate the original sidebar tab!
A fixed width area at the left to open the sidebar item

**Comment by crazko** [comment]
Fixed in newest version `0.5.0`. To make it work it is also needed to upgrade TiddlyWiki to `5.2.1`.
