### ISSUE TITLE
[IDEA] Krystal on medium screen

### ISSUE THREAD

**Issue by kookma** [crazko/krystal#32]
While Krystal works best on Large screen, it seems under width=960px Krystal uses vertical layout!  Headers accumulate the center in several rows! I may suggest to use a top or bottom row to arrange few header items as in Notebook!

![image](https://user-images.githubusercontent.com/830394/115654985-8556dd00-a347-11eb-936a-c3cf82798c47.png)

**Workaround**
- Use a bottom or top ribbon
- put some of essential items on that ribbon not all of them to prevent cluttering
- https://nicolas.petton.fr/tw/notebook.html gives some good ideas

**Comment by arunnbabu81** [comment]
I use Notebook theme along with Krystal. Notebook theme gets enabled only when opened in mobiles (using a hack provided by Nicolas Petton). See this issue. https://github.com/crazko/krystal/issues/28

**Comment by crazko** [comment]
> put some of essential items on that ribbon not all of them to prevent cluttering

As it is hard to decide what's really essential I've added an option to customize parts of the header for small and big viewport specifically. It can be done with `$:/plugins/rmnvsl/krystal/header` and `$:/plugins/rmnvsl/krystal/header-small` tags. Please, check https://crazko.github.io/krystal/#Customizable%20header.
