### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by theSherwood** [crazko/krystal#33]
Just wanted to say thank you for this theme. Fantastic work

**Comment by arunnbabu81** [comment]
@theSherwood pardon me for asking it here. Mentat was a nice addition to TW. Do you plan to update it to work with TW5.1.23

**Comment by theSherwood** [comment]
@arunnbabu81 I appreciate you saying so! But unfortunately, no. I haven't done any TW development in over a year and I don't have any plans to return in the near term. I didn't even realize Mentat was broken on the latest.

**Comment by arunnbabu81** [comment]
If upgraded to TW 5.1.23, I was not able to save tiddlers in Mentat. I had opened a [issue](https://github.com/theSherwood/Mentat/issues/25) sometime back.

**Comment by crazko** [comment]
Thank you @theSherwood, this is much appreciated!

**Comment by hukacode** [comment]
Hello @crazko 

Thank you for your time and great efforts for this theme.
Do you have template files of this theme, just HTML/JS/CSS (without TiddlyWiki code)?

I found this great theme a few days ago but I am not good at JS and don't know TW. So I would like to port to pure HTML/JS/CSS.

Anyway, I appreciate that. Thanks

**Comment by crazko** [comment]
Thank you for your kind words @hukacode.

Unfortunately, I do not have a template that can be used outside TW. I developed Krystal on the top of the basic TW theme and its code. For sure, it could be extracted, but one would need at least some HTML/CSS skills for that.
