### ISSUE TITLE
[bug] "Sidebar" tiddlers not rendered when using w/ TW 5.2.1 

### ISSUE THREAD

**Issue by scuerda** [crazko/krystal#39]
Installing plugin into a node-based tw created w/ 5.2.1 results in the following rendering error:

<img width="1118" alt="Screen Shot 2021-12-28 at 10 20 52 AM" src="https://user-images.githubusercontent.com/1843960/147581053-4e8bdca5-590b-41b7-b87b-146ecd29234b.png">

Steps to reproduce.

1. Create a new wiki w/ node cli `tiddlywiki mynewwiki --init server`
2. Create a plugins directory
3. Copy the plugin into the plugins directory
4. Launch server

I confirmed that if I downgrade to TW 5.1.23, the sidebar is working correctly. I assume that this is a minor incompatibility issue, but I am new to the TW world and haven't been able to track down a changelog that would help me start looking for discrepencies.

**Comment by arunnbabu81** [comment]
https://github.com/Jermolene/TiddlyWiki5/issues/6369#issuecomment-1000970854

This might be useful for your issue

**Comment by scuerda** [comment]
@arunnbabu81 oh interesting. That does look like the issue I am experiencing. Thanks for the link!

**Comment by scuerda** [comment]
Ok, closing this issue for now. Hopefully the link back to the discussion in the TW repo will help anyone else who runs in to this issue.

**Comment by scuerda** [comment]
Here were my steps to fix, derived from @kookma suggestion.

1. Open the `$:/config/ViewTemplateBodyFilters/system` tiddler
2. Clone it to `$:/myconfig/ViewTemplateBodyFilters/system`
3. Replace the text w/ `[tag[$:/tags/SideBar]then[$:/core/ui/ViewTemplate/body/default]]`
4. Add the `list-before` field w/ value of `$:/config/ViewTemplateBodyFilters/system`

**Comment by crazko** [comment]
Thank you all for the effort. I was working on upgrade to TW 5.2.0 and haven't noticed the newest release. Will try to put aforementioned suggestions into the new version of Krystal.
