### ISSUE TITLE
Right side of screen cut off

### ISSUE THREAD

**Issue by noa-no-h** [crazko/krystal#40]
First of all, thank you for your amazing work. I love this plugin. 

I took a short break from using it and when I re-enabled it, I got this weird bug. When I open more than two tiddlers, the right side of the screen gets cut off:

<img width="1435" alt="Screen Shot 2022-02-22 at 7 47 23 PM" src="https://user-images.githubusercontent.com/86935909/155249504-33425336-e0e5-4726-b04a-c1d4b6175b03.png">

I was unable to reproduce it with a newly downloaded copy of tw but a fried who just started using it a month ago had the same thing happen. 

Since I helped set up my friend's tw, we have the same plugins and we're both using github to save. So I wondered whether one of our plugins was the culprit. But after disabling them all, the problem persisted. 

Any suggestions for what to try next/any idea what's going on? 

Thanks!

**Comment by noa-no-h** [comment]
That works! Thank you so much, both for the incredibly quick reply and for the simple fix!

**Comment by arunnbabu81** [comment]
I too had similar experience in the past. I found this solution somewhere in the tiddlywiki community at that time. Happy to share it with you. Thanks to tobibeer for creating this solution

**Comment by crazko** [comment]
Glad to hear that you like it, @noa-no-h! It's weird that the sidebar is the case as Krystal config makes it hidden.

I suppose the sidebar state was recovered when you turned Krystal off by some subsequent actions and it didn't restore once Kystal was enabled again. This tiddler `$:/state/sidebar` should contain "no".

Thanks @arunnbabu81 for such a fast response. That's incredible :)
