### ISSUE TITLE
Layout will be broken when we drag scroll too fast

### ISSUE THREAD

**Issue by hukacode** [crazko/krystal#47]
Hello,

I'm not good at English so please see my gif.
![layout-broken](https://user-images.githubusercontent.com/3462200/159673380-3bf7b587-9c98-43fb-9648-91741d00de45.gif)

This is steps to reproduce:
1. Go to https://crazko.github.io/krystal/ and open these notes like this image:
![image](https://user-images.githubusercontent.com/3462200/159672153-865f2178-374d-482c-a3d7-f40a986d790e.png)
2. Drag horizontal scroll bar from right to left (or left to right), the layout will be:
![image](https://user-images.githubusercontent.com/3462200/159672868-6a9f3666-0688-4ac2-9ed5-af88fa71c976.png)

**Comment by arunnbabu81** [comment]
I also have experienced it for sometime now. I thought it was due to some tweaks I made in my wiki.

**Comment by hukacode** [comment]
@arunnbabu81 
I workaround by change from `100` to `10`, `const throttledTiddlerFrameEffects = throttle(tiddlerFrameEffects, 10);`

**Comment by arunnbabu81** [comment]
> @arunnbabu81 I workaround by change from `100` to `10`, `const throttledTiddlerFrameEffects = throttle(tiddlerFrameEffects, 10);`

@hukacode  Thanks for sharing

**Comment by crazko** [comment]
Adding for future reference. https://tiddlywiki.com/#WidgetMessage%3A%20tm-scroll
