### ISSUE TITLE
Maximize tiddler not working with whitespace theme

### ISSUE THREAD

**Issue by arunnbabu81** [crazko/krystal#49]
I am not able to maximize the tiddler when [whitespce theme](http://j.d.whitespace.tiddlyspot.com/#) is active in my wiki.

See a demo [here](https://krytsal-whitespace.tiddlyhost.com/).

**Comment by crazko** [comment]
There are some many plugins used in your demo. It'd be really hard to debug the origin of the error. If you can, please provide a demo with least plugins possible (just Krystal and whitespace theme) without any modifications.

**Comment by arunnbabu81** [comment]
I was able to sort it out.

https://github.com/crazko/krystal/discussions/45#discussioncomment-2663415

check the link in this wiki
