### ISSUE TITLE
Import tiddler is blank

### ISSUE THREAD

**Issue by fkohrt** [crazko/krystal#5]
Dragging links on the story river or using the Import button summons the Import tiddler at the left, but it is blank:

![Screenshot_2020-06-08 My TiddlyWiki — a non-linear personal web notebook](https://user-images.githubusercontent.com/12914806/83989164-d6373000-a945-11ea-8cb7-0bc1077e6999.png)

**Comment by crazko** [comment]
Thanks for the report. Can you check it with the latest version if still occurs?

**Comment by fkohrt** [comment]
Cool, that solved it!
