### ISSUE TITLE
The notification to save and reload after installing a plugin hide the main toolbar in the top

### ISSUE THREAD

**Issue by woodwm** [crazko/krystal#51]
After install a plugin, Tiddlywiki show a notification to save and reload, but this notification hide the main toolbar in the top including save button. The user have to close the notification to click the save button.

**Comment by crazko** [comment]
Do you mean this notification? 
![image](https://user-images.githubusercontent.com/1255989/169537352-178b8888-6073-4f67-b015-534e2b93bf17.png)

If so, save button is also inside it, so it is not needed to close it first to be able to save the page.

**Comment by woodwm** [comment]
Yes.
