### ISSUE TITLE
Conflict with TiddlyMap

### ISSUE THREAD

**Issue by lucasbordeau** [crazko/krystal#52]
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/26528466/170700195-14f31c94-e5e3-4daa-8ea8-91eedebdba18.png">

Steps to reproduce :

1. Get a new wiki running
2. Install TiddlyMap http://tiddlymap.org/
3. Install Krystal
4. Click on the Map menu 

The problem seems to come from the removed sidebar, and `tc-sidebar-scrollable` element

**Comment by arunnbabu81** [comment]
> <img alt="image" width="1490" src="https://user-images.githubusercontent.com/26528466/170700195-14f31c94-e5e3-4daa-8ea8-91eedebdba18.png">
> 
> Steps to reproduce :
> 
> 1. Get a new wiki running
> 2. Install TiddlyMap http://tiddlymap.org/
> 3. Install Krystal
> 4. Click on the Map menu
> 
> The problem seems to come from the removed sidebar, and `tc-sidebar-scrollable` element

https://github.com/felixhayashi/TW5-TiddlyMap/issues/422#issue-1206118585

Is this helpful for you

**Comment by crazko** [comment]
I was able to successfully install TiddlyMap with the instructions linked in @arunnbabu81 comment above.

**Comment by crazko** [comment]
Closing this, as this does not seem to be a problem with Krystal directly. In general, it would be very difficult to make it compatible with every imaginable plugin.
