### ISSUE TITLE
Make Krystal a PageLayout

### ISSUE THREAD

**Issue by peterhajas** [crazko/krystal#54]
TiddlyWiki now has support for custom page layouts:

https://tiddlywiki.com/#Alternative%20page%20layouts

It'd be great if Krystal were a page layout I could switch to with the page layout shortcut

**Comment by arunnbabu81** [comment]
@crazko is there any possibility of a horizontal layout in the future?

**Comment by crazko** [comment]
I'd need to dive into the docs to know more about this feature. I think it might be a valuable improvement.

**Comment by arunnbabu81** [comment]
Take a look at this captivate layout 

https://cdruan.github.io/tw5-captivate/#%24%3A%2Fthemes%2Fcdr%2Fcaptivate%2Fui%2FPageLayout

**Comment by crazko** [comment]
Thanks. Please, lets continue in [the discussion](https://github.com/crazko/krystal/discussions/50). I will close this for now.
