### ISSUE TITLE
how to remove formatting for thinner screens

### ISSUE THREAD

**Issue by noa-no-h** [crazko/krystal#57]
Hello!
I'd like to make my tiddlywiki so that it doesn't automatically change to the vertical scrolling version on thinner page widths but instead keeps the krystal look. I tried setting Sidebar breakpoint to 0px with no luck. (I did this by making that single change on the https://crazko.github.io/krystal/ page). What am I missing?

Thanks!
Noa

**Comment by crazko** [comment]
Hi, CSS media queries are used in various places. So you'd need to change all of them, not only one.

Check:

- https://github.com/crazko/krystal/blob/master/plugins/rmnvsl/krystal/header.css#L28
- https://github.com/crazko/krystal/blob/master/plugins/rmnvsl/krystal/river.css#L20
- https://github.com/crazko/krystal/blob/master/plugins/rmnvsl/krystal/search.css#L36
- https://github.com/crazko/krystal/blob/master/plugins/rmnvsl/krystal/title.css#L7

**Comment by noa-no-h** [comment]
Thank you! That worked perfectly!
