### ISSUE TITLE
Unable to view installed tab plugins

### ISSUE THREAD

**Issue by yazmsw** [crazko/krystal#8]
I love this template: it is so fun to use! But I am having difficulty viewing plugins that should appear in the top header. For example, the [favorite plugin](https://kookma.github.io/TW-Favorites/), does not show up beside the Open/Recent/More tab options. The theme seems to not allow tabbed subheadings. Is this a design of the template or something that can be modified to allow?

**Comment by crazko** [comment]
Hi, I'm glad you like it. The configuration of header "tab" links was a bit hardcoded, but I've just changed it so it behaves more like Sidebar tabs. The link from the Favorite plugin should be visible now.

You can follow this new simple [header configuration page](https://crazko.github.io/krystal/#Customizable%20Header) for more info. Let me know, if this suits your case.

**Comment by yazmsw** [comment]
Oh you are awesome! I do have a stupid question: how do I get your latest updates? I'm using TiddlyDesktop, rather than Github. Should I grab your latest version from https://crazko.github.io/krystal/ or should I try and download the updated files individually from Github?

**Comment by crazko** [comment]
I don't know how TiddlyDesktop works, but I assume that the update process stays the same.
Drag & drop the link `$:/plugins/rmnvsl/krystal` mentioned in the [Installation section](https://crazko.github.io/krystal/#Krystal) to your TiddlyWiki. It should ask you to import the plugin & replace old version with the new one.
Better to make a backup before, just in case something went bad.

**Comment by yazmsw** [comment]
Excellent, thanks so much. Kudos to you for putting together this beautiful template!

**Comment by crazko** [comment]
Thanks!
