### ISSUE TITLE
Exported Static Site is broken

### ISSUE THREAD

**Issue by idelem** [crazko/krystal#9]
I really like this theme, but it seems that the exported html file is not functional. (links give wrong results, etc) Would you please take a look? Thanks

**Comment by crazko** [comment]
I haven't tried export yet. How do you do that?

**Comment by idelem** [comment]
Click on "tools" in the nav bar, then press 

![image](https://user-images.githubusercontent.com/25763288/88145299-cee59080-cc2c-11ea-9d54-a7a7e64c2701.png)

A pop-up will show available formats, among which html. 

I don't expect the static file to be exactly the same layout as the live version, as I know that would be difficult. It'd be nice to just list all the tiddlers.

**Comment by crazko** [comment]
Thanks, I'll try to check it. Hopefully only some CSS additions are needed.

**Comment by crazko** [comment]
Hey, please take a look at a new version. Static export should be more usable now.
Let me know if you have more suggestions for improvements!
